#!/usr/bin/env python
"""
no more embarrasing "removed pdb, sorry" commits

install
-------

save it as .git/hooks/pre-commit giving +x permission
"""

import sys
from subprocess import Popen, PIPE

proc = Popen(['git', 'grep', '-E', '-n', '[ ;]i?pdb', '--', '*.py'], stdout=PIPE)
pdb_check, _ = proc.communicate()
if proc.returncode == 0:
    print("\033[31mPdb breakpoint found, shame on you! Please remove before commiting.\033[39m")
    print(pdb_check)
    sys.exit(-1)
